policy_type: BCMeanFlowPolicy
image_embed_size: 64
text_embed_size: 32
cond_predict_scale: true

diffusion_step_embed_dim: 128
down_dims:
- 256
- 512  
- 1024 

horizon: 16
kernel_size: 5
n_action_steps: 8
n_groups: 8
n_obs_steps: 2
flow_ratio: 0.5
image_encoder_hot: False
time_dist: ['lognorm', -0.4, 1.0]
jvp_api: 'autograd'
defaults:
    # - data_augmentation@color_aug: batch_wise_img_color_jitter_group_aug.yaml
    # - data_augmentation@translation_aug: translation_aug.yaml
    - image_encoder: resnet_encoder
    - language_encoder: mlp_encoder